fixtures:
  repositories:
    stdlib:     'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    foreman:    'git://github.com/theforeman/puppet-foreman.git'
    concat:     'git://github.com/puppetlabs/puppetlabs-concat'
    postgresql: 'git://github.com/puppetlabs/puppetlabs-postgresql.git'
  symlinks:
    candlepin: "#{source_dir}"
