fixtures:
  repositories:
    stdlib:     'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    extlib:     'git://github.com/puppet-community/puppet-extlib.git'
    concat:     'git://github.com/puppetlabs/puppetlabs-concat'
    postgresql: 'git://github.com/puppetlabs/puppetlabs-postgresql.git'
  symlinks:
    candlepin: "#{source_dir}"
