fixtures:
  repositories:
    stdlib:     'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    extlib:
      repo: 'git://github.com/puppet-community/puppet-extlib'
      ref:  'v0.11.3'
    concat:     'git://github.com/puppetlabs/puppetlabs-concat'
    postgresql: 'git://github.com/puppetlabs/puppetlabs-postgresql.git'
  symlinks:
    candlepin: "#{source_dir}"
